from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class Preset:
    name: str
    time: List[str]
    performance: List[str]
    energy: List[str]
    domain: Optional[str] = None
    default_rolling: int = 10
    tooltips: Optional[Dict[str, str]] = None


# Helper to keep lists deduplicated but ordered
def _kw(*items):
    return list(dict.fromkeys([s.strip() for s in items if s]))


# ------------------------------------------------------------------
# Generic "catch all" aliases so every preset can recognize
# many extra column names. With these, each preset now
# supports many possible names across time, performance, and energy.
# ------------------------------------------------------------------
GENERIC_TIME = [
    "time",
    "t",
    "timestamp",
    "date",
    "datetime",
    "index",
    "row",
    "sample_index",
    "id",
    "step",
    "step_index",
    "iteration",
    "iter",
    "epoch",
    "cycle",
    "batch",
    "batch_id",
    "run",
    "run_id",
    "trial",
    "trial_id",
    "episode",
    "episode_id",
    "round",
    "round_id",
    "phase",
    "phase_id",
    "period",
    "period_index",
    "window",
    "window_index",
    "timepoint",
    "time_point",
    "time_idx",
    "tick",
    "frame",
    "frame_idx",
    "sample",
    "sample_time",
    "day",
    "day_index",
    "week",
    "week_index",
    "month",
    "month_index",
    "year",
    "year_index",
    "minute",
    "minutes",
    "hour",
    "hours",
    "second",
    "seconds",
    "ms",
    "millisecond",
    "microsecond",
    "nanosecond",
    "time_1",
    "time_2",
    "time_3",
    "time_4",
    "time_5",
    "time_6",
    "time_7",
    "time_8",
    "time_9",
    "time_10",
    # extra generic time like fields
    "survey",
    "cast",
    "profile",
    "dive",
    "trip",
    "haul",
    "set",
    "tow",
    "visit",
    "campaign_day",
    "cohort_day",
    "season",
    "day_of_week",
    "mission_time",
    # additional generic time aliases
    "created_at",
    "updated_at",
    "ts",
    "timestamp_utc",
    "datetime_utc",
    "date_time",
    "log_time",
    "recorded_at",
    "measurement_time",
]

GENERIC_PERF = [
    "performance",
    "output",
    "score",
    "quality",
    "efficiency",
    "effectiveness",
    "gain",
    "benefit",
    "result",
    "success_rate",
    "success",
    "reward",
    "utility",
    "impact",
    "metric",
    "metric_value",
    "metric_1",
    "metric_2",
    "metric_3",
    "metric_4",
    "metric_5",
    "metric_6",
    "metric_7",
    "metric_8",
    "metric_9",
    "metric_10",
    "metric_11",
    "metric_12",
    "metric_13",
    "metric_14",
    "metric_15",
    "metric_16",
    "metric_17",
    "metric_18",
    "metric_19",
    "metric_20",
    "metric_21",
    "metric_22",
    "metric_23",
    "metric_24",
    "metric_25",
    "metric_26",
    "metric_27",
    "metric_28",
    "metric_29",
    "metric_30",
    "metric_31",
    "metric_32",
    "metric_33",
    "metric_34",
    "metric_35",
    "metric_36",
    "metric_37",
    "metric_38",
    "metric_39",
    "metric_40",
    "kpi",
    "kpi_1",
    "kpi_2",
    "kpi_3",
    "kpi_4",
    "kpi_5",
    "kpi_6",
    "kpi_7",
    "kpi_8",
    "kpi_9",
    "kpi_10",
    "throughput",
    "yield",
    "stability",
    "coherence",
    "repair",
    "repair_rate",
    "improvement",
    "delta",
    "delta_perf",
    "delta_performance",
    "accuracy",
    "acc",
    "loss_inv",
    "cost_inv",
    "return",
    "roi",
    "signal",
    "signal_to_noise",
    "snr",
    "precision",
    "recall",
    "f1",
    "auc",
    "roc_auc",
    "lift",
    "index_value",
    "health",
    "health_score",
    "score_1",
    "score_2",
    "score_3",
    "score_4",
    "score_5",
    # extra science and domain outputs
    "viability",
    "growth",
    "growth_rate",
    "fitness",
    "survival",
    "calcification",
    "recruitment",
    "photosynthesis",
    "chlorophyll",
    "chl",
    "coverage",
    "abundance",
    "richness",
    "diversity",
    "shannon",
    "shannon_index",
    "cpue",
    "biomass",
    "juvenile_density",
    "live_coral_cover",
    "oxygen",
    "fluorescence",
    "feed_conversion_inv",
    "soh",
    "capacity_retained",
    # business and marketing outcomes
    "conversions",
    "revenue",
    "sales",
    "signups",
    "leads",
    "purchases",
    "orders",
    "subscriptions",
    "new_customers",
    "ltv",
    "clv",
    "engagement",
    "engagement_rate",
    "bounce_rate_inv",
    "unsub_rate_inv",
    # additional generic performance aliases
    "loss_reduction",
    "mse",
    "rmse",
    "mae",
    "mape",
    "r2",
    "nll_inv",
    "logloss_inv",
    "throughput_per_sec",
    "rate_per_min",
    "successes",
    "failures_inv",
    "events_processed",
    "tasks_completed",
    "uptime",
    "availability",
    "stability_index",
    "health_index",
]

GENERIC_ENERGY = [
    "energy",
    "energy_used",
    "energy_spent",
    "energy_consumed",
    "effort",
    "work",
    "cost",
    "costs",
    "budget",
    "spend",
    "usage",
    "load",
    "tokens",
    "flops",
    "time_spent",
    "duration",
    "iterations",
    "steps",
    "resources",
    "resource_use",
    "resource_usage",
    "volume",
    "capacity",
    "requests",
    "calls",
    "trials",
    "samples",
    "dose",
    "intensity",
    "power",
    "power_use",
    "power_draw",
    "heat",
    "temperature",
    "stress",
    "strain",
    "input",
    "input_level",
    "control",
    "control_signal",
    "effort_units",
    "units_used",
    "attempts",
    "tries",
    "retries",
    "cycles",
    "cycle_count",
    "n_steps",
    "n_tokens",
    "n_events",
    "n_actions",
    "n_updates",
    "energy_1",
    "energy_2",
    "energy_3",
    "energy_4",
    "energy_5",
    "energy_6",
    "energy_7",
    "energy_8",
    "energy_9",
    "energy_10",
    "energy_11",
    "energy_12",
    "energy_13",
    "energy_14",
    "energy_15",
    "energy_16",
    "energy_17",
    "energy_18",
    "energy_19",
    "energy_20",
    "cost_1",
    "cost_2",
    "cost_3",
    "cost_4",
    "cost_5",
    "cost_6",
    "cost_7",
    "cost_8",
    "cost_9",
    "cost_10",
    # extra scientific and domain inputs
    "stressor",
    "par",
    "light",
    "temp",
    "pco2",
    "salinity",
    "nutrients",
    "nitrate",
    "no3",
    "phosphate",
    "po4",
    "silicate",
    "si",
    "feed",
    "aeration_power",
    "oxygenation",
    "water_exchange",
    "pump_power",
    "ship_time",
    "fuel",
    "cast_depth",
    "niskin_trips",
    "soak_time",
    "net_hours",
    "trawl_hours",
    "ecosystem_respiration_g_c_m2_day",
    # marketing and traffic proxies
    "ad_spend",
    "media_spend",
    "impressions",
    "imps",
    "clicks",
    "sessions",
    "visits",
    "traffic",
    "reach",
    "views",
    "emails_sent",
    "sms_sent",
    "messages_sent",
    "touches",
    # additional generic energy and effort aliases
    "loss",
    "penalty",
    "latency",
    "latency_ms",
    "response_time",
    "response_time_ms",
    "cpu_time",
    "wall_time",
    "wallclock_time",
    "memory",
    "memory_used",
    "disk_io",
    "network_io",
    "requests_total",
    "errors",
    "error_count",
    "retries_count",
    "gas_used",
    "fee",
    "fee_paid",
    "token_count",
]


PRESETS: Dict[str, Preset] = {
    # Core AI and Biology
    "AI": Preset(
        name="AI",
        time=_kw(
            "step",
            "iteration",
            "epoch",
            "update",
            "round",
            "time",
            "t",
            "global_step",
            "wall_clock_hours",
            "train_step",
            "eval_step",
            "episode",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "accuracy",
            "train_accuracy",
            "val_accuracy",
            "eval_accuracy",
            "f1",
            "f1_macro",
            "f1_micro",
            "reward",
            "episode_return",
            "score",
            "coherence",
            "loss_inv",
            "loss_reduction",
            "bleu",
            "rouge",
            "perplexity_inv",
            "exact_match",
            "mse_inv",
            "mae_inv",
            "log_likelihood",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "tokens",
            "tokens_processed",
            "effective_tokens",
            "tokens_seen",
            "compute",
            "flops",
            "gpu_hours",
            "energy",
            "power_draw",
            "cost",
            "gradient_updates",
            "optimizer_steps",
            "lr",
            "batch_size",
            "batch_tokens",
            "steps",
            "wall_time_hours",
            *GENERIC_ENERGY,
        ),
        domain="run_id",
        default_rolling=50,
        tooltips={
            "Performance": "Use accuracy, F1, reward, loss_inv, or exact_match to track model quality.",
            "Energy": "Use tokens, flops, gpu_hours, or cost as the effort axis.",
            "Time": "Step, epoch, or wall_clock_hours for training curves.",
            "Domain": "Group by run_id, model_name, or dataset.",
        },
    ),
    "Biology": Preset(
        name="Biology",
        time=_kw(
            "time",
            "t",
            "hours",
            "days",
            "day",
            "sample_time",
            "cycle",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "viability",
            "cell_viability",
            "function",
            "yield",
            "recovery",
            "signal",
            "od",
            "od600",
            "growth",
            "growth_rate",
            "fitness",
            "normalized_response",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "dose",
            "dose_mg_kg",
            "concentration",
            "stressor",
            "input",
            "energy",
            "treatment",
            "drug",
            "compound",
            "radiation",
            "uv_dose",
            "temperature",
            *GENERIC_ENERGY,
        ),
        domain="condition",
        default_rolling=10,
        tooltips={
            "Performance": "Use viability, growth_rate, or function as biological repair or recovery.",
            "Energy": "Use dose, concentration, or stressor level as input cost.",
            "Time": "Hours or days after treatment or perturbation.",
            "Domain": "Group by condition, plate, or replicate.",
        },
    ),

    # Ecology / Environmental recovery
    "Ecology": Preset(
        name="Ecology",
        time=_kw(
            "date",
            "day",
            "time",
            "t",
            "sample_time",
            "event_date",
            "sampling_event",
            "season",
            "year",
            "month",
            *GENERIC_TIME,
        ),
        performance=_kw(
            # Biological condition / ΔR signals
            "richness",
            "species_richness",
            "taxa_richness",
            "abundance",
            "total_abundance",
            "density",
            "biomass",
            "diversity",
            "shannon",
            "shannon_index",
            "simpson",
            "evenness",
            "EPT",
            "EPT_percent",
            "EPT_pct",
            "health_index",
            "ibi",
            "condition",
            "growth_rate",
            "productivity",
            "cover",
            "canopy",
            "functional_group",
            # Allow all generic performance as backups
            *GENERIC_PERF,
        ),
        energy=_kw(
            # Environmental energy inputs / stressors
            "nitrate",
            "no3",
            "nitrite",
            "no2",
            "ammonium",
            "nh4",
            "tn",
            "total_n",
            "tp",
            "total_p",
            "phosphate",
            "po4",
            "silicate",
            "si",
            # stable isotopes = perfect energy proxy
            "d13c",
            "δ13c",
            "delta13c",
            "d15n",
            "δ15n",
            "delta15n",
            # physicochemical drivers
            "temperature",
            "temp",
            "do",
            "oxygen",
            "conductivity",
            "cond",
            "salinity",
            "ph",
            # hydrology as energy and disturbance
            "discharge",
            "flow",
            "velocity",
            "stage",
            # habitat stress / disturbance / cost
            "disturbance_intensity",
            "treatment_level",
            "stress",
            "light",
            "par",
            "radiation",
            # generic backup energy terms
            *GENERIC_ENERGY,
        ),
        domain="site",
        default_rolling=5,
        tooltips={
            "Performance": "Use biological condition variables such as richness, abundance, biomass, diversity, EPT percent, IBI, or growth_rate as ΔR (repair).",
            "Energy": "Use environmental drivers such as NO3, NH4, PO4, TN or TP, δ13C or δ15N, temperature, flow, or disturbance_intensity as E (effort or cost).",
            "Time": "Use date, season, sampling_event, or sample_time for ecological time series.",
            "Domain": "Use site, reach, station, stream, habitat, or sampling location as domains to compare drift and recovery across environments.",
        },
    ),

    # Marine specific biology preset
    "Marine Biology": Preset(
        name="Marine Biology",
        time=_kw(
            "time",
            "t",
            "date",
            "eventdate",
            "event_date",
            "eventtime",
            "event_time",
            "day",
            "haul",
            "cast",
            "tow",
            "dive_time",
            "sample_time",
            "season",
            "day_of_year",
            "yearday",
            "timestamp",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "abundance",
            "density",
            "biomass",
            "cpue",
            "cpua",
            "richness",
            "diversity",
            "shannon_index",
            "health_index",
            "cover",
            "chlorophyll",
            "chlorophyll_a",
            "growth",
            "survival",
            "gross_primary_prod_g_c_m2_day",
            "gpp",
            "npp",
            "net_primary_prod_g_c_m2_day",
            "nep",
            "oxygen_production",
            "poc",
            "doc",
            "individualcount",
            "individual_count",
            "occurrencestatus",
            "presence",
            "presence_absence",
            "live_coral_cover",
            "juvenile_density",
            "calcification",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "effort",
            "trawls",
            "tows",
            "casts",
            "transects",
            "volume_filtered",
            "distance",
            "ship_time",
            "dive_hours",
            "ecosystem_respiration_g_c_m2_day",
            "respiration",
            "er",
            "par",
            "par_mol_photons_m2_day",
            "light",
            "temperature",
            "sst",
            "nutrients",
            "no3",
            "po4",
            "si",
            "cost",
            "input",
            # depth and vertical structure as energy proxies
            "depth",
            "minimumdepth",
            "maximumdepth",
            "minimumdepthinmeters",
            "maximumdepthinmeters",
            "min_depth",
            "max_depth",
            "verbatimdepth",
            "verbatimdepthinterval",
            "bottom_depth",
            "sample_depth",
            # sampling effort style axes
            "samplingeffort",
            "sampling_effort",
            *GENERIC_ENERGY,
        ),
        domain="station",
        default_rolling=10,
        tooltips={
            "Performance": "Use biomass, abundance, cpue, diversity, or GPP or NPP as ecosystem output or repair.",
            "Energy": "Use effort, tows, transects, volume_filtered, respiration, PAR, nutrients, or depth as sampling or stress cost.",
            "Time": "Use date, eventdate, season, or sample_time, often binned to daily, weekly, or seasonal steps.",
            "Domain": "Use station or site code (station, station_id, site) to compare locations or depth layers.",
        },
    ),

    "Robotics": Preset(
        name="Robotics",
        time=_kw(
            "t",
            "time",
            "cycle",
            "episode",
            "trial",
            "step",
            "tick",
            "rollout_step",
            "control_step",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "task_success",
            "success_rate",
            "score",
            "stability",
            "tracking_inv",
            "tracking_error_inv",
            "uptime",
            "mean_reward",
            "completion_rate",
            "episode_return",
            "collision_rate_inv",
            "fall_rate_inv",
            "path_accuracy",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "power",
            "torque_int",
            "battery_used",
            "battery_discharge",
            "energy",
            "effort",
            "cpu_load",
            "motor_current",
            "joint_torque",
            "control_effort",
            "temperature",
            *GENERIC_ENERGY,
        ),
        domain="robot_id",
        default_rolling=20,
        tooltips={
            "Performance": "Use success_rate, mean_reward, episode_return, tracking_inv, or path_accuracy for control quality.",
            "Energy": "Use battery_used, power, motor_current, joint_torque, or control_effort as task cost.",
            "Domain": "Group by robot_id, controller, or scenario.",
        },
    ),

    # Engineering and Ops
    "Manufacturing": Preset(
        name="Manufacturing",
        time=_kw("time", "shift", "batch", "lot", "t", "day", *GENERIC_TIME),
        performance=_kw(
            "yield",
            "good_units",
            "first_pass_yield",
            "throughput",
            "units_per_hour",
            "quality",
            "defect_rate_inv",
            "uptime",
            "oee",
            "scrap_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "power",
            "energy",
            "rework",
            "downtime",
            "input_cost",
            "labor_hours",
            "machine_hours",
            "material_used",
            *GENERIC_ENERGY,
        ),
        domain="line",
        default_rolling=30,
        tooltips={
            "Performance": "Use yield, good_units, or first_pass_yield as production output.",
            "Energy": "Use power, rework, downtime, or labor_hours as cost.",
            "Domain": "Group by line, machine, site, or product_family.",
        },
    ),
    "DevOps/SRE": Preset(
        name="DevOps/SRE",
        time=_kw("time", "t", "minute", "hour", "deploy", "build", "timestamp", *GENERIC_TIME),
        performance=_kw(
            "uptime",
            "availability",
            "slo_attained",
            "latency_inv",
            "p95_latency_inv",
            "error_rate_inv",
            "success_rate",
            "request_success",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "cpu",
            "cpu_percent",
            "mem",
            "memory_bytes",
            "cost",
            "requests",
            "writes",
            "build_minutes",
            "deploys",
            "pages",
            *GENERIC_ENERGY,
        ),
        domain="service",
        default_rolling=60,
        tooltips={
            "Performance": "Use uptime, availability, or latency_inv as reliability output.",
            "Energy": "Use cpu, memory, or requests as load and cost.",
            "Domain": "Group by service, cluster, or deployment ring.",
        },
    ),
    "Networking": Preset(
        name="Networking",
        time=_kw("time", "t", "slot", "interval", "timestamp", *GENERIC_TIME),
        performance=_kw(
            "throughput",
            "goodput",
            "availability",
            "pkt_success",
            "latency_inv",
            "packet_loss_inv",
            "jitter_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "tx_power",
            "bandwidth",
            "retries",
            "cost",
            "hops",
            "packets",
            "bytes",
            *GENERIC_ENERGY,
        ),
        domain="link",
        default_rolling=30,
        tooltips={
            "Performance": "Use throughput, goodput, or latency_inv to capture network health.",
            "Energy": "Use tx_power, bandwidth, retries, or packets as resource cost.",
            "Domain": "Group by link, interface, site, or vlan.",
        },
    ),
    "Aerospace": Preset(
        name="Aerospace",
        time=_kw("time", "t", "cycle", "flight", "mission_time", *GENERIC_TIME),
        performance=_kw(
            "mission_success",
            "stability",
            "tracking_inv",
            "fault_free_time",
            "navigation_accuracy",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "fuel",
            "power",
            "thrust_effort",
            "thermal_load",
            "control_effort",
            *GENERIC_ENERGY,
        ),
        domain="airframe_id",
        default_rolling=10,
        tooltips={
            "Performance": "Use mission_success, stability, or fault_free_time as mission outcome.",
            "Energy": "Use fuel, thrust_effort, or thermal_load as the cost side.",
            "Domain": "Group by airframe_id, mission_profile, or control_law.",
        },
    ),
    "Materials": Preset(
        name="Materials",
        time=_kw("time", "cycle", "step", "load_cycle", *GENERIC_TIME),
        performance=_kw(
            "strength",
            "conductivity",
            "hardness",
            "toughness",
            "yield_strength",
            "fatigue_life",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "temp",
            "load",
            "stress",
            "dose",
            "cycles",
            "strain_energy",
            *GENERIC_ENERGY,
        ),
        domain="sample_id",
        default_rolling=15,
        tooltips={
            "Performance": "Use strength, toughness, or fatigue_life as material endurance.",
            "Energy": "Use stress, cycles, or temp as applied load or degradation cost.",
            "Domain": "Group by sample_id, alloy, or treatment.",
        },
    ),

    # Science and Lab
    "Chemistry": Preset(
        name="Chemistry",
        time=_kw(
            "time",
            "t",
            "minutes",
            "minute",
            "min",
            "hours",
            "hour",
            "h",
            "time_min",
            "time_hr",
            "run",
            "cycle",
            "experiment_index",
            # richer chemistry specific time axes
            "reaction_time",
            "reaction_time_min",
            "timepoint",
            "time_point",
            "retention_time",
            "elution_time",
            "acquisition_time",
            "scan_time",
            "injection_time",
            "cycle_number",
            "cycle_index",
            *GENERIC_TIME,
        ),
        performance=_kw(
            # core reaction outputs
            "yield",
            "yield_percent",
            "yield_pct",
            "yield_theoretical",
            "yield_actual",
            "purity",
            "purity_percent",
            "selectivity",
            "selectivity_pct",
            "conversion",
            "conversion_percent",
            "conversion_rate",
            "conversion_pct",
            "product_conc",
            "product_concentration",
            "product_yield",
            "product_mass",
            "product_area",
            # kinetics and mechanism descriptors
            "rate",
            "rate_mmol_hr",
            "initial_rate",
            "rate_constant",
            "k_obs",
            "k_cat",
            "v_max",
            "turnover_number",
            "turnover_frequency",
            "activation_energy_inv",
            "arrhenius_constant",
            # advanced selectivity and stereochemistry
            "ee",
            "ee_pct",
            "dr",
            "rr",
            # instrumental and analytical outputs
            "signal",
            "area",
            "area_percent",
            "peak_area",
            "peak_height",
            "retention_index",
            "absorbance",
            "fluorescence",
            "nm_signal",
            "wavelength_abs",
            "intensity",
            "signal_to_noise",
            "baseline_corrected_signal",
            # electrochemistry performance style outputs
            "current_density",
            "peak_current",
            "onset_potential_inv",
            "faradaic_efficiency",
            "coulombic_efficiency",
            *GENERIC_PERF,
        ),
        energy=_kw(
            # reagents and load
            "reagent",
            "reagent_amount",
            "reagent_equiv",
            "equiv",
            "equivalents",
            "dose",
            "dose_mmol",
            "reagent_volume",
            "reagent_mass",
            "reagent_equivalents",
            "catalyst_mass",
            "catalyst_loading",
            "catalyst_loading_percent",
            "solvent_volume",
            "solvent_ratio",
            "substrate_moles",
            "reagent_moles",
            # thermodynamic and condition inputs
            "temp",
            "temp_c",
            "temperature",
            "temperature_c",
            "temp_k",
            "temperature_setpoint",
            "pressure",
            "pressure_atm",
            "pressure_psi",
            "time_at_temp",
            "energy",
            "energy_kj",
            "kwh",
            "power",
            "thermal_energy",
            "heat_input",
            "flow_rate",
            "residence_time",
            "mixing_speed",
            "rpm",
            "stir_rate",
            "stir_rate_rpm",
            "stirring_rate",
            # electrochemical and spectroscopic effort inputs
            "voltage",
            "current",
            "potential",
            "scan_rate",
            "electrolyte_conc",
            "excitation_wavelength",
            "laser_power",
            "integration_time",
            "cycles",
            *GENERIC_ENERGY,
        ),
        domain="reaction_id",
        default_rolling=10,
        tooltips={
            "Time": "Use reaction_time, minutes, hours, run, or cycle as your time or run index. Retention_time or scan_time for chromatography and spectroscopy.",
            "Performance": "Use yield, conversion, purity, selectivity, rate, or peak_area as reaction or assay output.",
            "Energy": "Use temp, energy_kj, reagent_equiv, catalyst_loading, flow_rate, or electrochemical inputs as energy or effort input.",
            "Domain": "Group by reaction_id, catalyst, solvent, substrate, or batch to compare conditions.",
        },
    ),

    # Omics preset with extra aliases
    "Omics/Gene Expression Ultra": Preset(
        name="Omics/Gene Expression Ultra",
        time=_kw(
            "time",
            "t",
            "index",
            "row",
            "rank",
            "gene_index",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "log2fc",
            "logFC",
            "log2_fold_change",
            "c19_c_log2fc",
            "c19_p_log2fc",
            "effect_size",
            "stat",
            "t_stat",
            "z_score",
            "signal",
            "score",
            "fold_change",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "padj",
            "p_adj",
            "pvalue",
            "p_value",
            "FDR",
            "fdr",
            "baseMean",
            "lfcSE",
            "counts",
            "sizeFactor",
            "dispersion",
            "variance",
            *GENERIC_ENERGY,
        ),
        domain="Symbol",
        default_rolling=1,
        tooltips={
            "Time": "If there is no real time column, the row index acts as a pseudo time axis.",
            "Performance": "Use log2 fold change, effect_size, or related statistics as output.",
            "Energy": "Use padj, p_value, baseMean, or similar columns as cost or perturbation strength.",
            "Domain": "Use the gene Symbol column to group per gene.",
        },
    ),

    "Physics Lab": Preset(
        name="Physics Lab",
        time=_kw("time", "t", "run", "shot", *GENERIC_TIME),
        performance=_kw(
            "signal",
            "stability",
            "coherence",
            "snr",
            "resolution",
            "lock_fraction",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "power",
            "fluence",
            "current",
            "shots",
            "cost",
            "exposure",
            *GENERIC_ENERGY,
        ),
        domain="experiment_id",
        default_rolling=10,
        tooltips={
            "Performance": "Use signal, coherence, or snr as experiment quality.",
            "Energy": "Use power, current, or shots as resource cost.",
            "Domain": "Group by experiment_id, configuration, or cavity.",
        },
    ),
    "Neuroscience": Preset(
        name="Neuroscience",
        time=_kw("time", "trial", "t", "block", *GENERIC_TIME),
        performance=_kw(
            "accuracy",
            "auc",
            "firing_sync",
            "connectivity",
            "score",
            "behavior_perf",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "stimulus",
            "stim_amplitude",
            "dose",
            "current",
            "effort",
            "trials",
            *GENERIC_ENERGY,
        ),
        domain="subject_id",
        default_rolling=20,
        tooltips={
            "Performance": "Use accuracy, behavior_perf, or connectivity as task output.",
            "Energy": "Use stimulus amplitude, dose, or trials as cost of adaptation.",
            "Domain": "Group by subject_id, region, or protocol.",
        },
    ),
    "Clinical Trials": Preset(
        name="Clinical Trials",
        time=_kw("visit", "day", "week", "time", *GENERIC_TIME),
        performance=_kw(
            "response",
            "remission",
            "score",
            "survival_inv",
            "function",
            "symptom_score_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "dose",
            "sessions",
            "adherence",
            "cost",
            "exposure",
            "pill_count",
            *GENERIC_ENERGY,
        ),
        domain="arm",
        default_rolling=8,
        tooltips={
            "Performance": "Use response, symptom_score_inv, or survival_inv as repair outcome.",
            "Energy": "Use dose, sessions, or adherence as effort and exposure.",
            "Domain": "Group by arm, site, or protocol.",
        },
    ),
    "Healthcare": Preset(
        name="Healthcare",
        time=_kw("time", "visit", "day", "t", *GENERIC_TIME),
        performance=_kw(
            "recovery",
            "response",
            "function",
            "score",
            "readmit_inv",
            "los_inv",
            "qaly",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "dose",
            "sessions",
            "cost",
            "effort",
            "treatment",
            "visits",
            *GENERIC_ENERGY,
        ),
        domain="patient_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use recovery, function, or readmit_inv as patient repair outcome.",
            "Energy": "Use cost, visits, or sessions as care effort.",
            "Domain": "Group by patient_id, ward, or condition_group.",
        },
    ),
    "Epidemiology/Public Health": Preset(
        name="Epidemiology/Public Health",
        time=_kw("date", "week", "time", *GENERIC_TIME),
        performance=_kw(
            "rt_inv",
            "incidence_inv",
            "coverage",
            "response_rate",
            "cases_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "doses",
            "tests",
            "cost",
            "interventions",
            "contacts_traced",
            *GENERIC_ENERGY,
        ),
        domain="region",
        default_rolling=7,
        tooltips={
            "Performance": "Use rt_inv, incidence_inv, or coverage as population repair or control.",
            "Energy": "Use doses, tests, and interventions as public health effort.",
            "Domain": "Group by region, age_group, or intervention_strategy.",
        },
    ),

    # Energy, Industry, Infrastructure
    "Energy/Grid": Preset(
        name="Energy/Grid",
        time=_kw("time", "interval", "t", *GENERIC_TIME),
        performance=_kw(
            "uptime",
            "availability",
            "efficiency",
            "output",
            "losses_inv",
            "renewable_fraction",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "load",
            "consumption",
            "cost",
            "curtailment",
            "effort",
            "peak_demand",
            *GENERIC_ENERGY,
        ),
        domain="asset_id",
        default_rolling=24,
        tooltips={
            "Performance": "Use efficiency, output, or uptime as grid health.",
            "Energy": "Use load, consumption, or curtailment as resource cost.",
            "Domain": "Group by asset_id, feeder, or region.",
        },
    ),

    # MAXED Battery / EV preset for NASA style cycle data
    "Battery/EV": Preset(
        name="Battery/EV",
        time=_kw(
            "cycle",
            "cycle_index",
            "cycle_number",
            "step",
            "step_index",
            "time",
            "t",
            "timestamp",
            "test_time",
            "test_time_s",
            "test_time_sec",
            "test_time_seconds",
            "test_time_min",
            "test_time_h",
            *GENERIC_TIME,
        ),
        performance=_kw(
            # capacity and state of health signals as ΔR
            "capacity",
            "capacity_ah",
            "capacity_mah",
            "charge_capacity",
            "discharge_capacity",
            "q_charge",
            "q_discharge",
            "Q_charge",
            "Q_discharge",
            "Qd",
            "Qc",
            "nominal_capacity",
            "rated_capacity",
            "capacity_retained",
            "capacity_retention",
            "capacity_fade_inv",
            "soh",
            "soh_percent",
            "state_of_health",
            "E_out",
            "E_in",
            "energy_out",
            "energy_in",
            "energy_throughput",
            "coulombic_efficiency",
            "roundtrip_efficiency",
            "efficiency",
            "internal_resistance_inv",
            "ir_inv",
            "dc_resistance_inv",
            "ac_resistance_inv",
            "range",
            "miles_per_kwh",
            "km_per_kwh",
            "cycle_life_remaining",
            # allow generic performance fallback
            *GENERIC_PERF,
        ),
        energy=_kw(
            # electrical and thermal load as E
            "current",
            "current_a",
            "current_amps",
            "current_ma",
            "I",
            "voltage",
            "voltage_v",
            "terminal_voltage",
            "V",
            "power",
            "power_w",
            "P",
            "charge_energy",
            "discharge_energy",
            "energy",
            "energy_in",
            "energy_out",
            "energy_throughput",
            "c_rate",
            "cr",
            "C_rate",
            "dod",
            "depth_of_discharge",
            "dod_percent",
            "soc",
            "state_of_charge",
            "soc_min",
            "soc_max",
            "temp",
            "temperature",
            "temperature_c",
            "cell_temp",
            "surface_temp",
            "env_temp",
            "ambient_temp",
            "cycle",
            "cycle_count",
            "step_index",
            "test_time_s",
            "test_time_sec",
            "time_charge",
            "time_discharge",
            "rest_time",
            # control and stress knobs
            "load_current",
            "load_power",
            "charge_current",
            "discharge_current",
            "charge_voltage",
            "discharge_voltage",
            "coolant_flow",
            "coolant_temp",
            "fan_speed",
            # generic energy and effort backups
            *GENERIC_ENERGY,
        ),
        domain="cell_id",
        default_rolling=25,
        tooltips={
            "Time": "Use cycle, cycle_index, cycle_number, or test_time columns as the horizontal axis.",
            "Performance": "Use capacity, discharge_capacity, Qd, capacity_retained, soh, or energy_out as the ΔR health signal.",
            "Energy": "Use current, voltage, power, c_rate, dod, cycle_count, or temperature as the E cost or load applied to the cell.",
            "Domain": "Use cell_id, battery_id, pack_id, or channel to compare multiple cells or packs.",
        },
    ),

    "Oil & Gas": Preset(
        name="Oil & Gas",
        time=_kw("time", "day", "shift", *GENERIC_TIME),
        performance=_kw(
            "production",
            "throughput",
            "uptime",
            "quality",
            "water_cut_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "power",
            "gas_injected",
            "steam",
            "cost",
            "water_cut",
            "lift_energy",
            *GENERIC_ENERGY,
        ),
        domain="well_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use production, throughput, or water_cut_inv as field output.",
            "Energy": "Use gas_injected, steam, or lift_energy as input cost.",
            "Domain": "Group by well_id, pad, or reservoir_zone.",
        },
    ),
    "Water/Wastewater": Preset(
        name="Water/Wastewater",
        time=_kw("time", "day", "interval", *GENERIC_TIME),
        performance=_kw(
            "removal_eff",
            "compliance",
            "uptime",
            "quality",
            "turbidity_inv",
            "bod_removal",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "flow",
            "power",
            "chem_dose",
            "cost",
            "pump_hours",
            *GENERIC_ENERGY,
        ),
        domain="plant",
        default_rolling=7,
        tooltips={
            "Performance": "Use removal_eff, compliance, or quality as treatment output.",
            "Energy": "Use flow, power, or chem_dose as treatment cost.",
            "Domain": "Group by plant, line, or basin.",
        },
    ),

    # Business and Data
    "Finance": Preset(
        name="Finance",
        time=_kw("date", "time", "t", "bar", "index", *GENERIC_TIME),
        performance=_kw(
            "return",
            "pnl",
            "sharpe",
            "alpha",
            "win_rate",
            "drawdown_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "risk",
            "var",
            "drawdown",
            "exposure",
            "volume",
            "cost",
            "margin",
            *GENERIC_ENERGY,
        ),
        domain="strategy",
        default_rolling=20,
        tooltips={
            "Performance": "Use return, pnl, or sharpe as capital growth signal.",
            "Energy": "Use exposure, risk, or drawdown as cost or danger.",
            "Domain": "Group by strategy, asset, or sector.",
        },
    ),
    "Economics/Macro": Preset(
        name="Economics/Macro",
        time=_kw("date", "quarter", "month", "t", *GENERIC_TIME),
        performance=_kw(
            "growth",
            "gdp_growth",
            "employment",
            "unemployment_inv",
            "inflation_inv",
            "output",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "spend",
            "government_spend",
            "rates",
            "interest_rates",
            "debt",
            "cost",
            "taxes",
            *GENERIC_ENERGY,
        ),
        domain="country",
        default_rolling=4,
        tooltips={
            "Performance": "Use gdp_growth, employment, or inflation_inv as macro health.",
            "Energy": "Use spend, rates, or debt as policy and cost levers.",
            "Domain": "Group by country, region, or sector.",
        },
    ),

    # Marketing
    "Marketing": Preset(
        name="Marketing",
        time=_kw(
            "date",
            "day",
            "week",
            "month",
            "time",
            "t",
            "campaign_start",
            "campaign_end",
            "timestamp",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "conversion_rate",
            "conv_rate",
            "cvr",
            "ctr",
            "click_through_rate",
            "roas",
            "rpc",
            "revenue",
            "sales",
            "signups",
            "leads",
            "purchases",
            "orders",
            "subscriptions",
            "new_customers",
            "retention",
            "engagement",
            "engagement_rate",
            "open_rate",
            "reply_rate",
            "bounce_rate_inv",
            "unsub_rate_inv",
            "ltv",
            "clv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "spend",
            "ad_spend",
            "budget",
            "media_spend",
            "cost",
            "cpc_denom",
            "cpa_denom",
            "cpv_denom",
            "impressions",
            "imps",
            "reach",
            "views",
            "sessions",
            "visits",
            "traffic",
            "clicks",
            "emails_sent",
            "sms_sent",
            "messages_sent",
            "touches",
            *GENERIC_ENERGY,
        ),
        domain="campaign",
        default_rolling=7,
        tooltips={
            "Performance": "Use conversion_rate, roas, or revenue as outcome.",
            "Energy": "Use spend, impressions, or touches as media effort.",
            "Domain": "Group by campaign, channel, or audience_segment.",
        },
    ),

    # Simple marketing preset
    "Marketing Simple": Preset(
        name="Marketing Simple",
        time=_kw(
            "date",
            "day",
            "week",
            "month",
            *GENERIC_TIME,
        ),
        performance=_kw(
            "conversions",
            "revenue",
            "sales",
            "signups",
            "leads",
            "purchases",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "spend",
            "ad_spend",
            "budget",
            "cost",
            "impressions",
            "clicks",
            *GENERIC_ENERGY,
        ),
        domain="campaign",
        default_rolling=7,
        tooltips={
            "Performance": "Put your result column here (conversions, sales, revenue).",
            "Energy": "Put your effort column here (spend, budget, impressions, clicks).",
            "Domain": "Use campaign or channel to see which lines are winners or losers.",
        },
    ),

    "Sales/CRM": Preset(
        name="Sales/CRM",
        time=_kw("date", "stage_time", "time", *GENERIC_TIME),
        performance=_kw(
            "close_rate",
            "revenue",
            "aov",
            "win_rate",
            "pipeline_velocity",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "leads",
            "calls",
            "emails",
            "meetings",
            "spend",
            "touches",
            *GENERIC_ENERGY,
        ),
        domain="rep_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use close_rate, win_rate, or revenue as sales output.",
            "Energy": "Use calls, meetings, or touches as sales effort.",
            "Domain": "Group by rep_id, territory, or segment.",
        },
    ),
    "Web Analytics": Preset(
        name="Web Analytics",
        time=_kw("date", "time", "t", *GENERIC_TIME),
        performance=_kw(
            "conversion",
            "conversion_rate",
            "retention",
            "latency_inv",
            "availability",
            "bounce_rate_inv",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "traffic",
            "sessions",
            "requests",
            "pageviews",
            "cost",
            "build_minutes",
            *GENERIC_ENERGY,
        ),
        domain="property",
        default_rolling=7,
        tooltips={
            "Performance": "Use conversion_rate, retention, or bounce_rate_inv as site quality.",
            "Energy": "Use sessions, requests, or cost as traffic load and spend.",
            "Domain": "Group by property, page_group, or device_type.",
        },
    ),
    "E-commerce": Preset(
        name="E-commerce",
        time=_kw("date", "time", "week", *GENERIC_TIME),
        performance=_kw(
            "gmv",
            "orders",
            "aov",
            "repeat_rate",
            "conversion_rate",
            "customer_value",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "ad_spend",
            "discount",
            "inventory",
            "shipping_cost",
            "traffic",
            *GENERIC_ENERGY,
        ),
        domain="store",
        default_rolling=7,
        tooltips={
            "Performance": "Use gmv, orders, or repeat_rate as shop output.",
            "Energy": "Use ad_spend, discount, or inventory as cost levers.",
            "Domain": "Group by store, category, or campaign.",
        },
    ),
    "Customer Support": Preset(
        name="Customer Support",
        time=_kw("date", "time", "t", *GENERIC_TIME),
        performance=_kw(
            "csat",
            "fst_inv",
            "first_response_time_inv",
            "nps",
            "resolution_rate",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "tickets",
            "agent_hours",
            "escalations",
            "cost",
            "handled_chats",
            *GENERIC_ENERGY,
        ),
        domain="queue",
        default_rolling=7,
        tooltips={
            "Performance": "Use csat, nps, or resolution_rate as support output.",
            "Energy": "Use tickets, agent_hours, or escalations as effort.",
            "Domain": "Group by queue, channel, or product.",
        },
    ),

    # Supply and Mobility
    "Supply Chain": Preset(
        name="Supply Chain",
        time=_kw("date", "time", "week", "month", *GENERIC_TIME),
        performance=_kw(
            "on_time_rate",
            "otif",
            "fill_rate",
            "service_level",
            "inventory_turns",
            *GENERIC_PERF,
        ),
        energy=_kw(
            "orders",
            "shipments",
            "miles",
            "transport_cost",
            "handling_cost",
            "warehouse_hours",
            *GENERIC_ENERGY,
        ),
        domain="lane",
        default_rolling=30,
        tooltips={
            "Performance": "Use on_time_rate, otif, or fill_rate as logistics output.",
            "Energy": "Use miles, transport_cost, or warehouse_hours as effort.",
            "Domain": "Group by lane, route, or dc.",
        },
    ),
}
