from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class Preset:
    name: str
    time: List[str]
    performance: List[str]
    energy: List[str]
    domain: Optional[str] = None
    default_rolling: int = 10
    tooltips: Optional[Dict[str, str]] = None


# Helper to keep lists short but useful
def _kw(*items):
    return list(dict.fromkeys([s.strip() for s in items if s]))


PRESETS: Dict[str, Preset] = {
    # Core AI and Biology
    "AI": Preset(
        name="AI",
        time=_kw(
            "step",
            "iteration",
            "epoch",
            "update",
            "round",
            "time",
            "t",
            "global_step",
            "wall_clock_hours",
            "train_step",
            "eval_step",
            "episode",
        ),
        performance=_kw(
            "accuracy",
            "train_accuracy",
            "val_accuracy",
            "eval_accuracy",
            "f1",
            "f1_macro",
            "f1_micro",
            "reward",
            "episode_return",
            "score",
            "coherence",
            "loss_inv",
            "loss_reduction",
            "bleu",
            "rouge",
            "perplexity_inv",
            "exact_match",
            "mse_inv",
            "mae_inv",
            "log_likelihood",
        ),
        energy=_kw(
            "tokens",
            "tokens_processed",
            "effective_tokens",
            "tokens_seen",
            "compute",
            "flops",
            "gpu_hours",
            "energy",
            "power_draw",
            "cost",
            "gradient_updates",
            "optimizer_steps",
            "lr",
            "batch_size",
            "batch_tokens",
            "steps",
            "wall_time_hours",
        ),
        domain="run_id",
        default_rolling=50,
        tooltips={
            "Performance": "Use accuracy, F1, reward, loss_inv, or exact_match to track model quality.",
            "Energy": "Use tokens, flops, gpu_hours, or cost as the effort axis.",
            "Time": "Step, epoch, or wall_clock_hours for training curves.",
            "Domain": "Group by run_id, model_name, or dataset.",
        },
    ),
    "Biology": Preset(
        name="Biology",
        time=_kw(
            "time",
            "t",
            "hours",
            "days",
            "day",
            "sample_time",
            "cycle",
        ),
        performance=_kw(
            "viability",
            "cell_viability",
            "function",
            "yield",
            "recovery",
            "signal",
            "od",
            "od600",
            "growth",
            "growth_rate",
            "fitness",
            "normalized_response",
        ),
        energy=_kw(
            "dose",
            "dose_mg_kg",
            "concentration",
            "stressor",
            "input",
            "energy",
            "treatment",
            "drug",
            "compound",
            "radiation",
            "uv_dose",
            "temperature",
        ),
        domain="condition",
        default_rolling=10,
        tooltips={
            "Performance": "Use viability, growth_rate, or function as biological repair or recovery.",
            "Energy": "Use dose, concentration, or stressor level as input cost.",
            "Time": "Hours or days after treatment or perturbation.",
            "Domain": "Group by condition, plate, or replicate.",
        },
    ),

    # Marine specific biology presets
    "Marine Biology": Preset(
        name="Marine Biology",
        time=_kw(
            "time",
            "t",
            "date",
            "day",
            "haul",
            "cast",
            "tow",
            "dive_time",
            "sample_time",
        ),
        performance=_kw(
            "abundance",
            "density",
            "biomass",
            "cpue",
            "cpua",
            "richness",
            "diversity",
            "shannon_index",
            "health_index",
            "cover",
            "chlorophyll",
            "chlorophyll_a",
            "growth",
            "survival",
        ),
        energy=_kw(
            "effort",
            "trawls",
            "tows",
            "casts",
            "transects",
            "volume_filtered",
            "distance",
            "ship_time",
            "dive_hours",
            "cost",
            "input",
        ),
        domain="station",
        default_rolling=10,
        tooltips={
            "Performance": "Use biomass, abundance, cpue, or diversity as ecosystem output.",
            "Energy": "Use effort, tows, transects, or volume_filtered as sampling cost.",
            "Time": "Date or sample_time, often binned to daily, weekly, or seasonal steps.",
            "Domain": "Use station, site, or depth_stratum for location splits.",
        },
    ),
    "Marine Biology v2": Preset(
        name="Marine Biology v2",
        time=_kw(
            "date",
            "time",
            "season",
            "day_of_year",
            "yearday",
            "timestamp",
        ),
        performance=_kw(
            "gross_primary_prod_g_c_m2_day",
            "gpp",
            "npp",
            "net_primary_prod_g_c_m2_day",
            "nep",
            "oxygen_production",
            "chlorophyll_a",
            "poc",
            "doc",
        ),
        energy=_kw(
            "ecosystem_respiration_g_c_m2_day",
            "respiration",
            "er",
            "par",
            "par_mol_photons_m2_day",
            "light",
            "temperature",
            "sst",
            "nutrients",
            "no3",
            "po4",
            "si",
        ),
        domain="station_id",
        default_rolling=10,
        tooltips={
            "GPP / NPP": "Use GPP or NPP as the primary production or repair axis.",
            "Respiration": "Ecosystem respiration is a proxy for maintenance cost and energy demand.",
            "Light and temperature": "PAR and temperature drive production and stress in coastal systems.",
            "Domain": "Use station_id or site_code to compare stations or depth layers.",
        },
    ),

    "Robotics": Preset(
        name="Robotics",
        time=_kw(
            "t",
            "time",
            "cycle",
            "episode",
            "trial",
            "step",
            "tick",
            "rollout_step",
            "control_step",
        ),
        performance=_kw(
            "task_success",
            "success_rate",
            "score",
            "stability",
            "tracking_inv",
            "tracking_error_inv",
            "uptime",
            "mean_reward",
            "completion_rate",
            "episode_return",
            "collision_rate_inv",
            "fall_rate_inv",
            "path_accuracy",
        ),
        energy=_kw(
            "power",
            "torque_int",
            "battery_used",
            "battery_discharge",
            "energy",
            "effort",
            "cpu_load",
            "motor_current",
            "joint_torque",
            "control_effort",
            "temperature",
        ),
        domain="robot_id",
        default_rolling=20,
        tooltips={
            "Performance": "Use success_rate, mean_reward, episode_return, tracking_inv, or path_accuracy for control quality.",
            "Energy": "Use battery_used, power, motor_current, joint_torque, or control_effort as task cost.",
            "Domain": "Group by robot_id, controller, or scenario.",
        },
    ),

    # Engineering and Ops
    "Manufacturing": Preset(
        name="Manufacturing",
        time=_kw("time", "shift", "batch", "lot", "t", "day"),
        performance=_kw(
            "yield",
            "good_units",
            "first_pass_yield",
            "throughput",
            "units_per_hour",
            "quality",
            "defect_rate_inv",
            "uptime",
            "oee",
            "scrap_inv",
        ),
        energy=_kw(
            "power",
            "energy",
            "rework",
            "downtime",
            "input_cost",
            "labor_hours",
            "machine_hours",
            "material_used",
        ),
        domain="line",
        default_rolling=30,
        tooltips={
            "Performance": "Use yield, good_units, or first_pass_yield as production output.",
            "Energy": "Use power, rework, downtime, or labor_hours as cost.",
            "Domain": "Group by line, machine, site, or product_family.",
        },
    ),
    "DevOps/SRE": Preset(
        name="DevOps/SRE",
        time=_kw("time", "t", "minute", "hour", "deploy", "build", "timestamp"),
        performance=_kw(
            "uptime",
            "availability",
            "slo_attained",
            "latency_inv",
            "p95_latency_inv",
            "error_rate_inv",
            "success_rate",
            "request_success",
        ),
        energy=_kw(
            "cpu",
            "cpu_percent",
            "mem",
            "memory_bytes",
            "cost",
            "requests",
            "writes",
            "build_minutes",
            "deploys",
            "pages",
        ),
        domain="service",
        default_rolling=60,
        tooltips={
            "Performance": "Use uptime, availability, or latency_inv as reliability output.",
            "Energy": "Use cpu, memory, or requests as load and cost.",
            "Domain": "Group by service, cluster, or deployment ring.",
        },
    ),
    "Networking": Preset(
        name="Networking",
        time=_kw("time", "t", "slot", "interval", "timestamp"),
        performance=_kw(
            "throughput",
            "goodput",
            "availability",
            "pkt_success",
            "latency_inv",
            "packet_loss_inv",
            "jitter_inv",
        ),
        energy=_kw(
            "tx_power",
            "bandwidth",
            "retries",
            "cost",
            "hops",
            "packets",
            "bytes",
        ),
        domain="link",
        default_rolling=30,
        tooltips={
            "Performance": "Use throughput, goodput, or latency_inv to capture network health.",
            "Energy": "Use tx_power, bandwidth, retries, or packets as resource cost.",
            "Domain": "Group by link, interface, site, or vlan.",
        },
    ),
    "Aerospace": Preset(
        name="Aerospace",
        time=_kw("time", "t", "cycle", "flight", "mission_time"),
        performance=_kw(
            "mission_success",
            "stability",
            "tracking_inv",
            "fault_free_time",
            "navigation_accuracy",
        ),
        energy=_kw(
            "fuel",
            "power",
            "thrust_effort",
            "thermal_load",
            "control_effort",
        ),
        domain="airframe_id",
        default_rolling=10,
        tooltips={
            "Performance": "Use mission_success, stability, or fault_free_time as mission outcome.",
            "Energy": "Use fuel, thrust_effort, or thermal_load as the cost side.",
            "Domain": "Group by airframe_id, mission_profile, or control_law.",
        },
    ),
    "Materials": Preset(
        name="Materials",
        time=_kw("time", "cycle", "step", "load_cycle"),
        performance=_kw(
            "strength",
            "conductivity",
            "hardness",
            "toughness",
            "yield_strength",
            "fatigue_life",
        ),
        energy=_kw(
            "temp",
            "load",
            "stress",
            "dose",
            "cycles",
            "strain_energy",
        ),
        domain="sample_id",
        default_rolling=15,
        tooltips={
            "Performance": "Use strength, toughness, or fatigue_life as material endurance.",
            "Energy": "Use stress, cycles, or temp as applied load or degradation cost.",
            "Domain": "Group by sample_id, alloy, or treatment.",
        },
    ),

    # Science and Lab
    "Chemistry": Preset(
        name="Chemistry",
        time=_kw(
            "time",
            "t",
            "minutes",
            "minute",
            "min",
            "hours",
            "hour",
            "h",
            "time_min",
            "time_hr",
            "run",
            "cycle",
            "experiment_index",
        ),
        performance=_kw(
            "yield",
            "yield_percent",
            "yield_pct",
            "purity",
            "purity_percent",
            "selectivity",
            "conversion",
            "conversion_percent",
            "product_conc",
            "product_concentration",
            "signal",
            "area",
            "area_percent",
            "rate",
            "rate_mmol_hr",
            "initial_rate",
        ),
        energy=_kw(
            "reagent",
            "reagent_amount",
            "reagent_equiv",
            "equiv",
            "equivalents",
            "dose",
            "dose_mmol",
            "temp",
            "temp_c",
            "temperature",
            "temperature_c",
            "time_at_temp",
            "energy",
            "energy_kj",
            "kwh",
            "power",
            "pressure",
            "cycles",
            "stir_rate",
            "stir_rate_rpm",
            "catalyst_loading",
            "catalyst_loading_percent",
        ),
        domain="reaction_id",
        default_rolling=10,
        tooltips={
            "Time": "Use minutes, hours, run, or cycle as your time or run index.",
            "Performance": "Use yield, conversion, purity, rate, or area_percent as reaction output.",
            "Energy": "Use temp, energy_kj, reagent_equiv, cycles, or catalyst_loading as energy or effort input.",
            "Domain": "Group by reaction_id, catalyst, solvent, or batch.",
        },
    ),

    # Omics preset with 30 possible column names across time, performance, energy
    "Omics/Gene Expression Ultra": Preset(
        name="Omics/Gene Expression Ultra",
        time=_kw(
            "time",
            "t",
            "index",
            "row",
            "rank",
            "gene_index",
        ),
        performance=_kw(
            "log2fc",
            "logFC",
            "log2_fold_change",
            "c19_c_log2fc",
            "c19_p_log2fc",
            "effect_size",
            "stat",
            "t_stat",
            "z_score",
            "signal",
            "score",
            "fold_change",
        ),
        energy=_kw(
            "padj",
            "p_adj",
            "pvalue",
            "p_value",
            "FDR",
            "fdr",
            "baseMean",
            "lfcSE",
            "counts",
            "sizeFactor",
            "dispersion",
            "variance",
        ),
        domain="Symbol",
        default_rolling=1,
        tooltips={
            "Time": "If there is no real time column, the row index acts as a pseudo time axis.",
            "Performance": "Use log2 fold change, effect_size, or related statistics as output.",
            "Energy": "Use padj, p_value, baseMean, or similar columns as cost or perturbation strength.",
            "Domain": "Use the gene Symbol column to group per gene.",
        },
    ),

    "Physics Lab": Preset(
        name="Physics Lab",
        time=_kw("time", "t", "run", "shot"),
        performance=_kw(
            "signal",
            "stability",
            "coherence",
            "snr",
            "resolution",
            "lock_fraction",
        ),
        energy=_kw(
            "power",
            "fluence",
            "current",
            "shots",
            "cost",
            "exposure",
        ),
        domain="experiment_id",
        default_rolling=10,
        tooltips={
            "Performance": "Use signal, coherence, or snr as experiment quality.",
            "Energy": "Use power, current, or shots as resource cost.",
            "Domain": "Group by experiment_id, configuration, or cavity.",
        },
    ),
    "Neuroscience": Preset(
        name="Neuroscience",
        time=_kw("time", "trial", "t", "block"),
        performance=_kw(
            "accuracy",
            "auc",
            "firing_sync",
            "connectivity",
            "score",
            "behavior_perf",
        ),
        energy=_kw(
            "stimulus",
            "stim_amplitude",
            "dose",
            "current",
            "effort",
            "trials",
        ),
        domain="subject_id",
        default_rolling=20,
        tooltips={
            "Performance": "Use accuracy, behavior_perf, or connectivity as task output.",
            "Energy": "Use stimulus amplitude, dose, or trials as cost of adaptation.",
            "Domain": "Group by subject_id, region, or protocol.",
        },
    ),
    "Clinical Trials": Preset(
        name="Clinical Trials",
        time=_kw("visit", "day", "week", "time"),
        performance=_kw(
            "response",
            "remission",
            "score",
            "survival_inv",
            "function",
            "symptom_score_inv",
        ),
        energy=_kw(
            "dose",
            "sessions",
            "adherence",
            "cost",
            "exposure",
            "pill_count",
        ),
        domain="arm",
        default_rolling=8,
        tooltips={
            "Performance": "Use response, symptom_score_inv, or survival_inv as repair outcome.",
            "Energy": "Use dose, sessions, or adherence as effort and exposure.",
            "Domain": "Group by arm, site, or protocol.",
        },
    ),
    "Healthcare": Preset(
        name="Healthcare",
        time=_kw("time", "visit", "day", "t"),
        performance=_kw(
            "recovery",
            "response",
            "function",
            "score",
            "readmit_inv",
            "los_inv",
            "qaly",
        ),
        energy=_kw(
            "dose",
            "sessions",
            "cost",
            "effort",
            "treatment",
            "visits",
        ),
        domain="patient_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use recovery, function, or readmit_inv as patient repair outcome.",
            "Energy": "Use cost, visits, or sessions as care effort.",
            "Domain": "Group by patient_id, ward, or condition_group.",
        },
    ),
    "Epidemiology/Public Health": Preset(
        name="Epidemiology/Public Health",
        time=_kw("date", "week", "time"),
        performance=_kw(
            "rt_inv",
            "incidence_inv",
            "coverage",
            "response_rate",
            "cases_inv",
        ),
        energy=_kw(
            "doses",
            "tests",
            "cost",
            "interventions",
            "contacts_traced",
        ),
        domain="region",
        default_rolling=7,
        tooltips={
            "Performance": "Use rt_inv, incidence_inv, or coverage as population repair or control.",
            "Energy": "Use doses, tests, and interventions as public health effort.",
            "Domain": "Group by region, age_group, or intervention_strategy.",
        },
    ),

    # Energy, Industry, Infrastructure
    "Energy/Grid": Preset(
        name="Energy/Grid",
        time=_kw("time", "interval", "t"),
        performance=_kw(
            "uptime",
            "availability",
            "efficiency",
            "output",
            "losses_inv",
            "renewable_fraction",
        ),
        energy=_kw(
            "load",
            "consumption",
            "cost",
            "curtailment",
            "effort",
            "peak_demand",
        ),
        domain="asset_id",
        default_rolling=24,
        tooltips={
            "Performance": "Use efficiency, output, or uptime as grid health.",
            "Energy": "Use load, consumption, or curtailment as resource cost.",
            "Domain": "Group by asset_id, feeder, or region.",
        },
    ),
    "Battery/EV": Preset(
        name="Battery/EV",
        time=_kw("cycle", "time", "t"),
        performance=_kw(
            "capacity_retained",
            "soh",
            "range",
            "efficiency",
            "internal_resistance_inv",
        ),
        energy=_kw(
            "charge",
            "discharge",
            "power",
            "c_rate",
            "temp",
            "dod",
        ),
        domain="pack_id",
        default_rolling=20,
        tooltips={
            "Performance": "Use capacity_retained, soh, or range as health and usefulness.",
            "Energy": "Use cycle count, c_rate, or power as load profile.",
            "Domain": "Group by pack_id, chemistry, or usage_profile.",
        },
    ),
    "Oil & Gas": Preset(
        name="Oil & Gas",
        time=_kw("time", "day", "shift"),
        performance=_kw(
            "production",
            "throughput",
            "uptime",
            "quality",
            "water_cut_inv",
        ),
        energy=_kw(
            "power",
            "gas_injected",
            "steam",
            "cost",
            "water_cut",
            "lift_energy",
        ),
        domain="well_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use production, throughput, or water_cut_inv as field output.",
            "Energy": "Use gas_injected, steam, or lift_energy as input cost.",
            "Domain": "Group by well_id, pad, or reservoir_zone.",
        },
    ),
    "Water/Wastewater": Preset(
        name="Water/Wastewater",
        time=_kw("time", "day", "interval"),
        performance=_kw(
            "removal_eff",
            "compliance",
            "uptime",
            "quality",
            "turbidity_inv",
            "bod_removal",
        ),
        energy=_kw(
            "flow",
            "power",
            "chem_dose",
            "cost",
            "pump_hours",
        ),
        domain="plant",
        default_rolling=7,
        tooltips={
            "Performance": "Use removal_eff, compliance, or quality as treatment output.",
            "Energy": "Use flow, power, or chem_dose as treatment cost.",
            "Domain": "Group by plant, line, or basin.",
        },
    ),

    # Business and Data
    "Finance": Preset(
        name="Finance",
        time=_kw("date", "time", "t", "bar", "index"),
        performance=_kw(
            "return",
            "pnl",
            "sharpe",
            "alpha",
            "win_rate",
            "drawdown_inv",
        ),
        energy=_kw(
            "risk",
            "var",
            "drawdown",
            "exposure",
            "volume",
            "cost",
            "margin",
        ),
        domain="strategy",
        default_rolling=20,
        tooltips={
            "Performance": "Use return, pnl, or sharpe as capital growth signal.",
            "Energy": "Use exposure, risk, or drawdown as cost or danger.",
            "Domain": "Group by strategy, asset, or sector.",
        },
    ),
    "Economics/Macro": Preset(
        name="Economics/Macro",
        time=_kw("date", "quarter", "month", "t"),
        performance=_kw(
            "growth",
            "gdp_growth",
            "employment",
            "unemployment_inv",
            "inflation_inv",
            "output",
        ),
        energy=_kw(
            "spend",
            "government_spend",
            "rates",
            "interest_rates",
            "debt",
            "cost",
            "taxes",
        ),
        domain="country",
        default_rolling=4,
        tooltips={
            "Performance": "Use gdp_growth, employment, or inflation_inv as macro health.",
            "Energy": "Use spend, rates, or debt as policy and cost levers.",
            "Domain": "Group by country, region, or sector.",
        },
    ),

    # Marketing
    "Marketing": Preset(
        name="Marketing",
        time=_kw(
            "date",
            "day",
            "week",
            "month",
            "time",
            "t",
            "campaign_start",
            "campaign_end",
            "timestamp",
        ),
        performance=_kw(
            "conversion_rate",
            "conv_rate",
            "cvr",
            "ctr",
            "click_through_rate",
            "roas",
            "rpc",
            "revenue",
            "sales",
            "signups",
            "leads",
            "purchases",
            "orders",
            "subscriptions",
            "new_customers",
            "retention",
            "engagement",
            "engagement_rate",
            "open_rate",
            "reply_rate",
            "bounce_rate_inv",
            "unsub_rate_inv",
            "ltv",
            "clv",
        ),
        energy=_kw(
            "spend",
            "ad_spend",
            "budget",
            "media_spend",
            "cost",
            "cpc_denom",
            "cpa_denom",
            "cpv_denom",
            "impressions",
            "imps",
            "reach",
            "views",
            "sessions",
            "visits",
            "traffic",
            "clicks",
            "emails_sent",
            "sms_sent",
            "messages_sent",
            "touches",
        ),
        domain="campaign",
        default_rolling=7,
        tooltips={
            "Performance": "Use conversion_rate, roas, or revenue as outcome.",
            "Energy": "Use spend, impressions, or touches as media effort.",
            "Domain": "Group by campaign, channel, or audience_segment.",
        },
    ),

    # Simple marketing preset
    "Marketing Simple": Preset(
        name="Marketing Simple",
        time=_kw(
            "date",
            "day",
            "week",
            "month",
        ),
        performance=_kw(
            "conversions",
            "revenue",
            "sales",
            "signups",
            "leads",
            "purchases",
        ),
        energy=_kw(
            "spend",
            "ad_spend",
            "budget",
            "cost",
            "impressions",
            "clicks",
        ),
        domain="campaign",
        default_rolling=7,
        tooltips={
            "Performance": "Put your result column here (conversions, sales, revenue).",
            "Energy": "Put your effort column here (spend, budget, impressions, clicks).",
            "Domain": "Use campaign or channel to see which lines are winners or losers.",
        },
    ),

    "Sales/CRM": Preset(
        name="Sales/CRM",
        time=_kw("date", "stage_time", "time"),
        performance=_kw(
            "close_rate",
            "revenue",
            "aov",
            "win_rate",
            "pipeline_velocity",
        ),
        energy=_kw(
            "leads",
            "calls",
            "emails",
            "meetings",
            "spend",
            "touches",
        ),
        domain="rep_id",
        default_rolling=14,
        tooltips={
            "Performance": "Use close_rate, win_rate, or revenue as sales output.",
            "Energy": "Use calls, meetings, or touches as sales effort.",
            "Domain": "Group by rep_id, territory, or segment.",
        },
    ),
    "Web Analytics": Preset(
        name="Web Analytics",
        time=_kw("date", "time", "t"),
        performance=_kw(
            "conversion",
            "conversion_rate",
            "retention",
            "latency_inv",
            "availability",
            "bounce_rate_inv",
        ),
        energy=_kw(
            "traffic",
            "sessions",
            "requests",
            "pageviews",
            "cost",
            "build_minutes",
        ),
        domain="property",
        default_rolling=7,
        tooltips={
            "Performance": "Use conversion_rate, retention, or bounce_rate_inv as site quality.",
            "Energy": "Use sessions, requests, or cost as traffic load and spend.",
            "Domain": "Group by property, page_group, or device_type.",
        },
    ),
    "E-commerce": Preset(
        name="E-commerce",
        time=_kw("date", "time", "week"),
        performance=_kw(
            "gmv",
            "orders",
            "aov",
            "repeat_rate",
            "conversion_rate",
            "customer_value",
        ),
        energy=_kw(
            "ad_spend",
            "discount",
            "inventory",
            "shipping_cost",
            "traffic",
        ),
        domain="store",
        default_rolling=7,
        tooltips={
            "Performance": "Use gmv, orders, or repeat_rate as shop output.",
            "Energy": "Use ad_spend, discount, or inventory as cost levers.",
            "Domain": "Group by store, category, or campaign.",
        },
    ),
    "Customer Support": Preset(
        name="Customer Support",
        time=_kw("date", "time", "t"),
        performance=_kw(
            "csat",
            "fst_inv",
            "first_response_time_inv",
            "nps",
            "resolution_rate",
        ),
        energy=_kw(
            "tickets",
            "agent_hours",
            "escalations",
            "cost",
            "handled_chats",
        ),
        domain="queue",
        default_rolling=7,
        tooltips={
            "Performance": "Use csat, nps, or resolution_rate as support output.",
            "Energy": "Use tickets, agent_hours, or escalations as effort.",
            "Domain": "Group by queue, channel, or product.",
        },
    ),

    # Supply and Mobility
    "Supply Chain": Preset(
        name="Supply Chain",
        time=_kw("date", "time", "week", "month"),
        performance=_kw(
            "on_time_rate",
            "otif",
            "fill_rate",
            "service_level",
            "inventory_turns",
        ),
        energy=_kw(
            "orders",
            "shipments",
            "miles",
            "transport_cost",
            "handling_cost",
            "warehouse_hours",
        ),
        domain="lane",
        default_rolling=30,
        tooltips={
            "Performance": "Use on_time_rate, otif, or fill_rate as logistics output.",
            "Energy": "Use miles, transport_cost, or warehouse_hours as effort.",
            "Domain": "Group by lane, route, or dc.",
        },
    ),
}
